development:
  adapter: postgresql
  encoding: unicode
  database: political_speech_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: political_speech_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: political_speech_production
  pool: 5
  timeout: 5000
